### ISSUE TITLE
ExamplePlugin

### ISSUE THREAD

**Issue by nnnlog** [organization/ExamplePlugins#1]
- 이번에 새로 만든 것과 hm님(if-Team)이 만든 것과 다른 건가요?
- 라이센스는 없는건가요?

**Comment by wsj7178** [comment]
Q1. 이번에 새로 만든 것과 hm님(if-Team)이 만든 것과 다른 건가요?
A. hm 님이 만든건 pmmp 플긴 예제. 이건 Nukkit 플긴 예제. 다르죠

Q2. 라이센스는 없는건가요?
A. @angelless 님이 대답해주실겁니다.

**Comment by nnnlog** [comment]
@wsj7178 아, 이게 누킷용 이군요...

**Comment by angelless** [comment]
@ParkChanSol 기본적으로 다른분들이 소스를 체험하고, 주석으로 그걸 해석하면서 
기본적인 플러그인개발의 발판을 만들고자 레포를 만들게 되었고,
적용되어있는 라이센스는 MIT입니다(수정후)

**Comment by HmHmmHm** [comment]
@angelless GPLv3는 라이센스 문제가 있을 것으로 생각되고 MIT라이센스가 좋을 것 같네요.

**Comment by angelless** [comment]
@HmHmmHm 감사합니다 
수정하도록 할게요

**Comment by nnnlog** [comment]
@angelless 답변 감사합니다

**Comment by nnnlog** [comment]
@angelless @HmHmmHm MIT 라이센스와 GPLv3 라이센스의 차이점은 뭔가요?
GPLv3은 코드 수정 금지인건 아는데, MIT을 잘 몰라서요

**Comment by wsj7178** [comment]
@ParkChanSol GPL v3 코드 수정 가능합니다. 대신 수정한 결과물도 GPLv3 그대로 적용해야 되요.
[GPL 설명](https://www.olis.or.kr/ossw/license/license/detail.do?lid=1072)
[MIT 설명](https://www.olis.or.kr/ossw/license/license/detail.do?lid=1006)

**Comment by ParkChanSol** [comment]
음... 감사합니다
이왕에 LGPL 라이센스도...
